# Generated by Django 4.1.3 on 2022-12-08 20:30

import accomodation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_apartment_checkin_date_apartment_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='checkout_date',
            field=models.DateField(validators=[accomodation.models.valid_checkout_date]),
        ),
    ]
