# Generated by Django 4.1.3 on 2022-12-08 20:42

import accomodation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomodation', '0003_alter_apartment_checkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='duration',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField(validators=[accomodation.models.valid_checkout_date])),
                ('duration', models.DurationField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
