# Generated by Django 4.1.3 on 2022-12-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0004_remove_apartment_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='made_payment',
            field=models.BooleanField(default=False),
        ),
    ]
