# Generated by Django 4.1.3 on 2022-12-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0005_book_made_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentImages',
            new_name='ApartmentImage',
        ),
    ]
