# Generated by Django 4.1.3 on 2022-12-08 21:20

import accomodation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0006_rename_apartmentimages_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.apartment', validators=[accomodation.models.validate_apartment_image_count]),
        ),
    ]
