# Generated by Django 4.1.3 on 2022-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0007_alter_apartmentimage_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='book',
            name='reference',
            field=models.CharField(default='dfadf43j3', max_length=100),
        ),
    ]
