# Generated by Django 4.1.3 on 2022-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0008_book_amount_book_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
