# Generated by Django 4.1.3 on 2022-12-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0009_alter_book_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.apartment', unique=True),
        ),
    ]
