# Generated by Django 4.1.3 on 2022-12-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0011_apartment_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100)),
                ('icon', models.TextField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.apartment')),
            ],
        ),
    ]
