# Generated by Django 4.1.3 on 2022-12-10 23:59

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0012_apartmentproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentproperty',
            name='icon',
            field=faicon.fields.FAIconField(max_length=50),
        ),
    ]
